### ISSUE TITLE
Trying to paste a very large BP string

### ISSUE THREAD

**Issue by jerodg** [rickyzhangca/fprints-xyz#13]
On paste of 10,026,673 bytes BP book:
BP: [Mega-Ultra City 0.zip](https://github.com/user-attachments/files/18267070/Mega-Ultra.City.0.zip)

Unexpected Application Error!
Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
    at jn (https://fprints.xyz/assets/js/index-B8NpnBzy.js:2:3339)
    at https://fprints.xyz/assets/js/index-B8NpnBzy.js:2:3435
    at Array.forEach (<anonymous>)
    at Object.jn [as getComponents] (https://fprints.xyz/assets/js/index-B8NpnBzy.js:2:3409)
    at Object.recommendTags (https://fprints.xyz/assets/js/index-B8NpnBzy.js:2:32548)
    at o (https://fprints.xyz/assets/js/index-B8NpnBzy.js:35:232585)
    at Dl (https://fprints.xyz/assets/js/index-B8NpnBzy.js:35:83301)
    at So (https://fprints.xyz/assets/js/index-B8NpnBzy.js:35:99108)
    at _o (https://fprints.xyz/assets/js/index-B8NpnBzy.js:35:98992)
    at So (https://fprints.xyz/assets/js/index-B8NpnBzy.js:35:99787)

**Comment by rickyzhangca** [comment]
hi there, lemme take a look, it is possible to share the string?

**Comment by jerodg** [comment]
Added BP, it's a BP book, are those supported?

**Comment by rickyzhangca** [comment]
yes bp supported, looking at the error it might be something to do with parsing a big book, if it's ok to post the string here or factoriobin.com it'll be super helpful for debugging!

**Comment by jerodg** [comment]
I edited the issue and attached it as a zip. (at the top of the issue description)
